#!/usr/bin/php
<?php

use Symfony\Component\Process\Process;

require __DIR__ . '/inc/bootstrap.php';

Lock::registerAutorelease();

$deployPrefix = '/srv/deploy/example.com_';
$symlinkTarget = '/srv/example.com';


$last = 0;
foreach (glob("$deployPrefix*") as $dir)
{
	$index = substr($dir, strlen($deployPrefix));
	if ($index > $last)
	{
		$last = $index;
	}
}

$path = $deployPrefix . ($last + 1);
mkdir($path);
echo "Checking-out to $path\n";
run('git archive ' . Refs::getRef() . ' | tar -xC ' . escapeshellarg($path));

echo "Coping previous config.local.neon\n";
run('cp ' . $symlinkTarget . 'app/config/config.local.neon ' . escapeshellarg("$path/app/config/"));

echo "Updating privileges\n";
run('chmod -R ug+rwx,o= ' . escapeshellarg($path));
run('chgrp -R webexpo ' . escapeshellarg($path));

echo "Writing deploy.txt\n";
$out = "Deployed on " . date('Y-m-d H:i:s') . "\n";
$out .= Refs::getCommit() . "\n";
run('echo ' . escapeshellarg($out) . ' > ' . escapeshellarg("$path/www/deploy.txt"));

echo "Blessing this build\n";
sleep(1);

echo "Running migrations\n";
run('php ' . escapeshellarg("$path/www/index.php") . ' migrations:migrate');

echo "Swapping symlinks\n";
run('unlink ' . $symlinkTarget . ' && ln -s ' . escapeshellarg($path) . ' ' . $symlinkTarget);

echo "Reloading worker\n";
run('sudo supervisorctl restart example:worker-00');

echo "Reloading php5-fpm\n";
run('sudo /etc/init.d/php5-fpm reload');

echo "Flushing redis\n";
run('redis-cli flushall');

// Flushing fs cache is not required because the freshly
// checked out directory does not have any temp files

// Flushing varnish is not required

echo "\033[1;32mDeploy successful\033[0m\n";

function run($command)
{
	$process = new Process($command);
	$process->run();
	if (!$process->isSuccessful())
	{
	    System::fail($process->getErrorOutput() ?: "Deploy failed on command:\n$command");
	}
}
