#!/usr/bin/php
<?php

require __DIR__ . '/inc/bootstrap.php';

Lock::check();
Lock::registerAutorelease();
Lock::create();

$refs = Refs::read();
$count = 0;
foreach ($refs as list($from, $to, $ref))
{
	$count++;
	if ($count > 1)
	{
		System::fail("Pushing to multiple refs not allowed");
	}
	if (!Refs::validate($ref))
	{
		System::fail("Push to $ref not allowed");
	}
}

// do not release lock, leave it for next hooks
Lock::disableAutorelease();
